### ISSUE TITLE
Option to configure persistent volume access modes

### ISSUE THREAD

**Issue by kalyan21** [bat-bs/helm-charts#31]
@hofq 
Thanks for maintaining this repo. 

Can we make this configurable by passing the value using values.yaml?

https://github.com/bat-bs/helm-charts/blob/f1b15443359385012140a6818041576ccfd84b79/charts/librechat/templates/persistentvolumeclaim.yaml#L8

We are inquiring because we use a rolling deployment strategy for our applications, and it encounters issues when using ReadWriteOnce. We would like to switch to ReadWriteMany to resolve this.

Do you see any risks in doing so? Happy to create a PR if you would like us to do the change. 

Thanks,
Kalyan

**Comment by hofq** [comment]
Thanks for the notice, added. Let me know if you run into other issues or feel free to reopen if it doesn't work

**Comment by kalyan21** [comment]
@hofq Thanks for changing this quickly. I have updated the chart to latest version but accessModes in PVCs are immutable so we have to recreate them. We are in the process of recreating them and I will let you know once we make changes and deploy it successfully.
